### ISSUE TITLE
disable text selection

### ISSUE THREAD

**Issue by ShahriarKh** [ShahriarKh/strapi-content-type-explorer#1]
The current behavior of text selection is annoying. Make field names unselectable or provide an option to toggle this.

**Comment by SalahAdDin** [comment]
@ShahriarKh are you still maintaining this?

**Comment by ShahriarKh** [comment]
Hi @SalahAdDin
Yes. I've been busy with some other projects recently, but yes, the project is alive!

**Comment by SalahAdDin** [comment]
@ShahriarKh Why is it not planned?

**Comment by ShahriarKh** [comment]
@SalahAdDin I think the cards are big enough to allow dragging them without text being annoyingly selected. Also, there might be use cases for selecting text, like the ability to copy the content type name.
