### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'withConfig')

### ISSUE THREAD

**Issue by nickkaradzha** [ShahriarKh/strapi-content-type-explorer#8]
After installing plugin, I wasn't able to use Strapi, because of this mistake:
<img width="1123" alt="image" src="https://github.com/ShahriarKh/strapi-content-type-explorer/assets/150792119/eaa7eb74-6d0d-4f0e-935a-6410e1a45b9c">
<img width="1602" alt="image" src="https://github.com/ShahriarKh/strapi-content-type-explorer/assets/150792119/1a316765-3db3-48b7-b530-61992c894704">
My Strapi version is v4.4.1.
My Node version is v16.14.2
I use Next.js v13.0.2

**Comment by ShahriarKh** [comment]
Hi @nickkaradzha
I tested with strapi `v4.15.5` and node `v18.17.0` and the plugin is working correctly.

Please try:
- upgrading to the latest version of strapi
- upgrading node version
- checking if another plugin or some other misconfiguration is causing the problem

**Comment by nickkaradzha** [comment]
Hi, @ShahriarKh! Thanks for reply.
