### ISSUE TITLE
Compatibility Issue with Node.js 20

### ISSUE THREAD

**Issue by AliKdhim87** [ShahriarKh/strapi-content-type-explorer#9]
# Compatibility Issue with Node.js 20

## Description

I'm encountering an issue with the "strapi-content-type-explorer" plugin when trying to run it with Node.js version 20.10.0. The error message indicates an incompatibility with the Node.js version.

## Environment

- Plugin Version: 0.1.1
- Strapi Version: 4.14.4
- Node.js Version: 20.10.0
- Operating System: ios

## Error Message

```shell
error strapi-content-type-explorer@0.1.1: The engine "node" is incompatible with this module. Expected version ">=14.19.1 <=18.x.x". Got "20.10.0"
```

## Steps to Reproduce

1. Install the "strapi-content-type-explorer" plugin.
2. Set Node.js version to 20.10.0.
3. Run Strapi.

## Possible Solutions

[If you have any suggestions for a solution or workaround, please provide them here.]

**Comment by ShahriarKh** [comment]
Thank you for reporting.
This should be fixed by updating the package.json file:
https://github.com/ShahriarKh/strapi-content-type-explorer/blob/1c2e3b3ed522eb8722e5db8fc966b80c0b73df98/package.json#L40
However, I need to review some code before publishing a new version. You can try modifying the file manually to see if it works until then.

**Comment by AliKdhim87** [comment]
Thanks @ShahriarKh  for your quick response. I tested it locally by adding support for Node.js version 20, and it works well! That's why I made this [PR](https://github.com/ShahriarKh/strapi-content-type-explorer/pull/10) to officially support Node.js version 20.

**Comment by ShahriarKh** [comment]
Thanks for your contribution. Merged it.
I will release a new version with some other improvements soon.
